# Generated by Django 5.2.11 on 2026-02-13 07:05

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='products_pr_search__98d711_gin'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='products_pr_slug_3edc0c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='products_pr_categor_9edb3d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='products_pr_is_acti_ca4d9a_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['price'], name='products_va_price_b46f78_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['product'], name='products_va_product_18d9cf_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['is_active'], name='products_va_is_acti_3e17d0_idx'),
        ),
    ]
